version: '3'

services:
  fedora-box:
    build:
      context: .
      dockerfile: Containerfile
    container_name: fedora-box
    image: fedora-box:1.0
    hostname: toolbox
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: sleep infinity
    working_dir: /home/batman
    user: batman
    userns_mode: keep-id
    environment:
      - UID=1000
      - GID=1000
      - SHELL=/bin/zsh
      - EDITOR=vim
    volumes:
      - ./data:/home/batman/data:z
