version: '3'

services:
  toolbox:
    build:
      context: .
      dockerfile: Containerfile
    container_name: toolbox
    image: toolbox:1.1
    hostname: toolbox
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: sleep infinity
    working_dir: /home/batman
    user: batman
    userns_mode: keep-id
    environment:
      - UID=1000
      - GID=1000
      - SHELL=/bin/zsh
      - EDITOR=vim
    volumes:
      - ./data:/home/batman/shared:z
      - ~/.ssh:/home/batman/.ssh:ro,Z
