FROM quay.io/fedora/fedora:latest

LABEL project="toolbox" \
      os="fedora" \
      type="testing" \
      maintainer="yourname@example.com" \
      version="1.1"

RUN dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    && dnf install -y https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
    && dnf update -y \
    && dnf install -y \
    sudo \
    shadow-utils \
    curl \
    wget2 \
    tree \
    git \
    zsh \
    vim \
    tar \
    gzip \
    && dnf -y clean all

ARG USERNAME=batman
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN useradd -m -u 1000 -s /bin/zsh $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME
WORKDIR /home/$USERNAME

RUN rm -f /home/$USERNAME/.zshrc

COPY --chown=root:root vimrc /root/.vimrc
COPY --chown=$USERNAME:$USERNAME vimrc /home/batman/.vimrc
COPY --chown=$USERNAME:$USERNAME zshrc /home/batman/.zshrc

RUN mkdir -p /home/$USERNAME/shared && \
    chown -R 1000:1000 /home/$USERNAME/shared && \
    chmod 755 /home/$USERNAME/shared

RUN mkdir -p /home/$USERNAME/.ssh && \
    chown -R 1000:1000 /home/$USERNAME/.ssh && \
    chmod 0700 /home/$USERNAME/.ssh

USER $USERNAME 

ENV PATH="/home/${USERNAME}/.local/bin:${PATH}"

# python / ansible part

RUN dnf install -y \
    python3-pip

RUN pip install --user --no-cache-dir ansible-core


ENTRYPOINT ["/bin/zsh", "-c", "sleep infinity"]
CMD ["-l"]

